# Generated by Django 5.0.3 on 2024-04-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWSPORTAL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='NEWSPORTAL.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='NEWSPORTAL.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_en_us',
            field=models.ManyToManyField(null=True, through='NEWSPORTAL.PostCategory', to='NEWSPORTAL.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru',
            field=models.ManyToManyField(null=True, through='NEWSPORTAL.PostCategory', to='NEWSPORTAL.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='main_text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='main_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_created_at_en_us',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_rating_en_us',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_rating_ru',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_en_us',
            field=models.CharField(choices=[('ar', 'статья'), ('ns', 'новость')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_ru',
            field=models.CharField(choices=[('ar', 'статья'), ('ns', 'новость')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='PostCategory_en_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEWSPORTAL.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEWSPORTAL.post')),
            ],
            options={
                'verbose_name': 'post category [en-us]',
                'verbose_name_plural': 'post categorys [en-us]',
                'db_table': 'NEWSPORTAL_postcategory_en_us',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEWSPORTAL.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEWSPORTAL.post')),
            ],
            options={
                'verbose_name': 'post category [ru]',
                'verbose_name_plural': 'post categorys [ru]',
                'db_table': 'NEWSPORTAL_postcategory_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
